# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests
from bs4 import BeautifulSoup

def scrape_website_title(url):
  """Scrapes the title of a website."""
  try:
    response = requests.get(url)
    response.raise_for_status()  # Raise an exception for bad status codes
    soup = BeautifulSoup(response.content, 'html.parser')
    title_tag = soup.find('title')
    if title_tag:
      return title_tag.get_text()
    else:
      return "Title tag not found"
  except requests.exceptions.RequestException as e:
    return f"Error fetching the URL: {e}"
  except Exception as e:
    return f"An error occurred: {e}"

def web_scraper():
  """Runs the simple web scraper."""
  while True:
    url = input("Enter the URL to scrape (or 'exit' to quit): ")
    if url.lower() == 'exit':
      print("Exiting web scraper.")
      break
    title = scrape_website_title(url)
    print("Website Title:", title)

# Before running, install the necessary libraries:
# !pip install requests==2.31.0 beautifulsoup4==4.12.2
# Then run the web scraper:
# web_scraper()