# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests

def get_weather_data(api_key, city):
  """Fetches weather data from OpenWeatherMap API."""
  base_url = "http://api.openweathermap.org/data/2.5/weather?"
  complete_url = base_url + "appid=" + api_key + "&q=" + city
  response = requests.get(complete_url)
  return response.json()

def display_weather(data):
  """Displays the weather information."""
  if data["cod"] != "404":
    main = data["main"]
    current_temperature_kelvin = main["temp"]
    # Convert Kelvin to Celsius for easier understanding
    current_temperature_celsius = current_temperature_kelvin - 273.15
    current_pressure = main["pressure"]
    current_humidity = main["humidity"]
    weather_description = data["weather"][0]["description"]

    print(f"Temperature: {current_temperature_celsius:.2f}°C")
    print(f"Atmospheric pressure: {current_pressure} hPa")
    print(f"Humidity: {current_humidity}%")
    print(f"Description: {weather_description.capitalize()}")
  else:
    print("City Not Found")

def weather_app():
  """Runs the weather application."""
  api_key = "YOUR_API_KEY"  # Replace with your OpenWeatherMap API key

  if api_key == "YOUR_API_KEY":
      print("Please replace 'YOUR_API_KEY' with your actual OpenWeatherMap API key.")
      print("You can get one from: https://openweathermap.org/api")
      return

  while True:
    city = input("Enter city name (or 'exit' to quit): ")
    if city.lower() == 'exit':
      print("Exiting weather app.")
      break
    weather_data = get_weather_data(api_key, city)
    display_weather(weather_data)

# Before running, replace 'YOUR_API_KEY' with your actual API key
# You also need to install the 'requests' library: !pip install requests==2.31.0
# Then run the weather app:
# weather_app()